exclude: fixtures/|.gitlab-ci.yml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: static|README.md
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: ['--pytest-test-first']
        exclude: factories.py|async_factory.py
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=120, -S]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-spellcheck
          - dlint
          - darglint
          - mccabe
          - pep8-naming
        args: [ --classmethod-decorators=validator classmethod root_validator ]
  - repo: local
    hooks:
      - id: mypy
        name: Mypy check
        entry: mypy
        language: system
        args: [ backend/apps ]
        pass_filenames: false
      - id: isort
        name: isort
        entry: isort
        language: system
      - id: bandit-security-check
        name: Bandit security check
        entry: bandit
        args: [ -x, test ]
        language: system
        files: backend/apps/
      - id: safety-production-dependencies-check
        name: Safety production dependencies check
        entry: safety
        args: [ check, --ignore=42194, --ignore=44715, --full-report, --file]
        language: system
        files: requirements/production.txt
      - id: safety-development-dependencies-check
        name: Safety development dependencies check
        entry: safety
        args: [ check, --ignore=42194, --ignore=44715, --full-report, --file]
        language: system
        files: requirements/development.txt
